server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # ✅ Enables automatic Eureka discovery
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*" # In production, replace with "https://oikonpay.com"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10  # 10 requests per second
                redis-rate-limiter.burstCapacity: 20  # Max burst of 20
                redis-rate-limiter.requestedTokens: 1
        - id: ledger-service
          uri: lb://LEDGER-SERVICE
          predicates:
            - Path=/api/v1/transactions/**, /api/v1/wallets/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5   # Stricter limit for money ops
                redis-rate-limiter.burstCapacity: 10
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
  data:
    redis:
      host: oikon-redis
      port: 6379
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
